#!/bin/sh

if command -v wlr-randr >/dev/null 2>&1; then
  wlr-randr --output eDP-1 --mode 1920x1080@144.003 --scale 1.0 --transform normal --pos -1742,-127 >/dev/null 2>&1 &
fi

noctalia >/dev/null 2>&1 &
fcitx5 -d >/dev/null 2>&1 &
( sleep 3 && exec zalo ) >/dev/null 2>&1 &
( sleep 3 && exec flatpak run dev.vencord.Vesktop --no-sandbox --enable-speech-dispatcher --ozone-platform=wayland --enable-wayland-ime --wayland-text-input-version=3 --start-minimized ) >/dev/null 2>&1 &
