# Colors - Catppuccin Latte
background_opacity 0.70
font_size 12.0
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
hide_window_decorations yes
window_padding_width        10

# The basic colors
foreground            #160f0e
background            #eededa
cursor                #160f0e

# Black
color0                #101016
color8                #170f0e

# Red
color1                #27050a
color9                #22090c

# Green
color2                #0a1305
color10               #0a1305

# Yellow
color3                #190f03
color11               #190f03

# Blue
color4                #081024
color12               #07111d

# Magenta
color5                #1d0b16
color13               #1d0b16

# Cyan
color6                #061314
color14               #061314

# White
color7                #170f0e
color15               #121012
