# Colors - Catppuccin Latte
background_opacity 0.70
font_size 12.0
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
hide_window_decorations yes
window_padding_width        10

# The basic colors
foreground            #231917
background            #fff8f6
cursor                #231917

# Black
color0                #23232f
color8                #2d2220

# Red
color1                #4c0914
color9                #461218

# Green
color2                #15290b
color10               #15290b

# Yellow
color3                #352007
color11               #352007

# Blue
color4                #12224b
color12               #10253f

# Magenta
color5                #3d172f
color13               #3d172f

# Cyan
color6                #0c282a
color14               #0c282a

# White
color7                #2d2220
color15               #272326
