# Colors - Catppuccin Latte
allow_remote_control socket-only
listen_on unix:${XDG_RUNTIME_DIR}/kitty-{kitty_pid}.sock
auto_reload_config 0.1
background_opacity 0.70
font_size 12.0
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
hide_window_decorations yes
window_padding_width        10

# The basic colors
foreground            #21191c
background            #fff8f8
cursor                #21191c

# Black
color0                #28232a
color8                #2c2226

# Red
color1                #4b0b17
color9                #45131b

# Green
color2                #14290e
color10               #14290e

# Yellow
color3                #342009
color11               #342009

# Blue
color4                #11224b
color12               #0f2540

# Magenta
color5                #3c1731
color13               #3c1731

# Cyan
color6                #0b282b
color14               #0b282b

# White
color7                #2c2226
color15               #2a2227
